# Use the official Golang image as the build stage
FROM golang:1.20-alpine AS builder

# Set environment variables
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

# Set working directory
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod  ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the Go application
RUN go build -o todo-app main.go

# Use a minimal image for the final stage
FROM alpine:latest

# Set working directory
WORKDIR /root/

# Copy the binary from the builder stage
COPY --from=builder /app/todo-app .
COPY --from=builder /app/static ./static

# Expose port 8080
EXPOSE 8080

# Command to run the executable
CMD ["./todo-app"]
